repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: bandit
        name: bandit
        stages: [push]
        language: system
        entry: pipenv run bandit -r api -c "pyproject.toml"
        pass_filenames: false
        types: [python]

      - id: flake8
        name: flake8
        stages: [push]
        language: system
        entry: pipenv run flake8 api core
        pass_filenames: false
        types: [python]

      - id: pylint
        name: pylint
        stages: [push]
        language: system
        entry: pipenv run pylint api core
        pass_filenames: false
        types: [python]
